### ISSUE TITLE
Next Step Microgrant: <Your Title Here>

### ISSUE THREAD

**Issue by RobertoBarb** [filecoin-project/devgrants#1484] opened 2023-03-21 08:35 UTC
### 1. What is your project, and what problem does it solve? (max 100 words)
Filestock is a platform uses blockchain technology to protect and sell digital images. It ensures that photographers are fairly compensated for their work and that the rights to the images are clearly represented. It's a Web3 take on stock photography

### 2. Project links
  
Link to Github repo: https://github.com/file-stock
Link to demo or website: https://frontend-filestock.vercel.app/
License: MIT

  
### 3. a) How is IPFS, Filecoin, or related technology used in this project?
We developed used two different repositories, one for the smart contract and the second one for the front end. The three contracts, developed using solidity, are respectively

FileStock.sol: storage and purchase of the images,
RightsNFT: mints the ERC1155 token to decrypt the images stored on lighthouse
CreatorNFT: mints the NFT token, the one which gives the rights to receive the proceedings from the image sales.
The frontend was built with NextJS, dividing the organization in pages that represent the steps the user does to upload the files and to buy them.

All the files are stored in lighthouse, which let us deploy them both encrypted and not, in order to protect the original ones and show to the user the images with the watermark applied.

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? 
  
| Number | Grant Deliverable       | Briefly describe how you will meet deliverable objectives  | Timeframe (within 3 months)|
| :---   | :------                 | :---                                                       | :---                       | 
| 1.     |                        |      Tag system insertion and search functionalities      |       3 weeks                     |  3 weeks
| 2.     |                         |      Complete seller profile                     |     2 weeks                       |  2 weeks
| 3.     |                         |      Complete buyer profile                   |      2 weeks                      |  2 weeks
| 4.     |                         |     Improve UX and user experience      |     2 weeks                       |  2 weeks

### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
https://ethglobal.com/showcase/filestock-fdo7k
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project. 
- Simone Ruggeri: Project Manager
- Roberto Barbone: fullstack developer 
- Simone Russomanno: frontend developer
* How did you learn about our microgrant program? From the ETHGlobal SpaceWarp Hackathon 
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum) ETHGlobal Spacewarp
  * Please link to your hackathon submission https://ethglobal.com/showcase/filestock-fdo7k

**Comment by eshon** [comment] 2023-04-18 20:31
Closing as duplicate of https://github.com/filecoin-project/devgrants/issues/1485

**Closed by eshon** 2023-04-18 20:31 UTC
Labels: Micro Grant, fvm
